### ISSUE TITLE
Can't press anything

### ISSUE THREAD

**Issue by Tigre2Games** [PsychPorting/FNF-PsychEngine-0.6.3-Mobile#4]
### Describe your bug here.

When I started the game for the first time and I get the flashing lights warning. I try to give both options but it won't let me give them. Even the option assaulted me. And then I put on a GamePad to try to pass the option and I did itAnd well, I put on a GamePad to try to pass the option and I succeeded, but if I take off the GamePad again it won't let me touch anything.

Uploading km_20240615_360p_50f_20240615_175626.mp4…

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
psych conflict, delete old and reinstall from releases again

**Comment by Tigre2Games** [comment]
> psych conflict, delete old and reinstall from releases again

I did the same thing, but look... I'll show you my video so you can see the problem in detail. https://www.mediafire.com/file/0hzwmy8nvc4pa01/km_20240615_360p_50f_20240615_175626.mp4/file

**Comment by mcagabe19** [comment]
@Tigre2Games I want u to try release build again

**Comment by mcagabe19** [comment]
closing as fixed
