### ISSUE TITLE
Mods Folder Bug

### ISSUE THREAD

**Issue by Z4CK1234** [PsychPorting/FNF-PsychEngine-0.6.3-Mobile#6]
### Describe your bug here.

When I Try To Open The Mods Folder It Crashes The Game Hope You Fix The Bug.
 
Here's The Bug:
Invalid char 34 at position 198
/opt/hostedtoolcache/haxe/4.2.4/x64/std/haxe/format/JsonParser.invalidChar() [line 318]
/opt/hostedtoolcache/haxe/4.2.4/x64/std/haxe/format/JsonParser.parseRec() [line 96]
/opt/hostedtoolcache/haxe/4.2.4/x64/std/haxe/format/JsonParser.doParse() [line 57]
ModsMenuState.new() [line 738]
ModsMenuState.create() [line 331]
flixel/FlxGame.switchState() [line 637]
flixel/FlxGame.update() [line 724]
flixel/FlxGame.step() [line 677]
flixel/FlxGame.onEnterFrame() [line 545]
openfl/events/EventDispatcher.__dispatchEvent() [line 402]
openfl/display/DisplayObject.__dispatch() [line 1399]

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I Didn't Edit Anything

**Comment by mcagabe19** [comment]
json issue, check if missing or added "," accidently

**Comment by Z4CK1234** [comment]
What JSON Is Missing?

**Comment by Z4CK1234** [comment]
Which Json Is Missing?

**Comment by mcagabe19** [comment]
json is not missing and idk what is it, you needed figure out
