### ISSUE TITLE
Mods Folder Bug External (Forgot To Say External)

### ISSUE THREAD

**Issue by Z4CK1234** [PsychPorting/FNF-PsychEngine-0.6.3-Mobile#7]
### Describe your problem here.

I Still Can't Figure It Out The Problem I Try Checking Every Folder Inside The Assets But I Can't See The Problem... Please Just Fix The Problem.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I Didn't Edit Anything

**Comment by mcagabe19** [comment]
figure out yourself and don't open duplicate issues. If you still keep do that, I'll have to block you
