### ISSUE TITLE
I'm Sorry For Duplicating The Issues.

### ISSUE THREAD

**Issue by Z4CK1234** [PsychPorting/FNF-PsychEngine-0.6.3-Mobile#8]
### Describe your problem here.

Hear Me Out Okay? I Try External, The Mods Folder Doesn't Work, I Change It Into External_OBB Or External_Media The Mods Folder Is Working But I Can't Copy Any Mods In My External Folder That's All, But Please Don't Block Me I'm Just Asking Questions And I Didn't Mean To Duplicate The Issues, But This Is My Last Issue.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I Didn't Edit Anything

**Comment by moxie-coder** [comment]
you were already warned to stop you fucking moron
